export const ENV = {
  LOCAL: 'local',
  DEV: 'dev',
  SIT: 'sit',
  PRE: 'pre',
  PROD: 'prod',
};

export const ERROR = {
  PARAMS: 'PARAMS',
  TIMEOUT: 'TIMEOUT',
  NETWORK: 'NETWORK',
  SYSTEM: 'SYSTEM',
  LOGIN: 'LOGIN',
  GATEWAY: 'GATEWAY',
  VALIDATION: 'VALIDATION',
  TAOBAOBINDALIPAY: 'TAOBAOBINDALIPAY',
  REGISTERWALLET: 'REGISTERWALLET',
  NOALIPAYID: 'NOALIPAYID',
  TRUSTLOGINERROR: 'TRUSTLOGINERROR',
  SIGNIN: 'SIGNIN', // 未登陆容器
  GETSIGNPARAMSERROR: 'GETSIGNPARAMSERROR', // 获取信登串失败
};

export const TIMEOUT = 30000;
